[tool.poetry]
name = "merkly"
version = "0.1.0"
readme = "README.md"
description = "🌳 The simple and easy implementation of Merkle Tree"
authors = ["Lucas Oliveira <olivmath@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

pypi-token = "pypi-AgEIcHlwaS5vcmcCJGE2MTRiNDFmLWRlNDUtNGExZS1hNWMzLTEwMDc0ZGU4MWYxYgACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgTvz5BIY-sju_ou6wgnfxClx_Yu0R2YXN_3kOcElqN28"